const express = require("express")
const http = require("http")
const app = express()
const server = http.createServer(app)
const PORT = process.env.PORT || 5000
app.use(express.urlencoded({ extended: true }))
const user = require('./apis/user')
const post = require('./apis/post')
const auth = require('./apis/auth')
const friend = require('./apis/friend')
const login = require('./apis/login')
const {connectSocket} = require('./chat/chatting')
app.use('/',user)
app.use('/',post)
app.use('/',auth)
app.use('/',friend)
app.use('/',login)
connectSocket(server)
server.listen(PORT, () => console.log(`server is running in port: ${PORT}`))